### ISSUE TITLE
design question: external reactor

### ISSUE THREAD

**Issue by yoshuawuyts** [ashleygwilliams/changes-stream-rust#14]
Heya, newbie question here. I was wondering why you chose to bundle in the event loop _inside_ the lib instead of taking in an external event loop. I know this was impossible in `mio` (at least I tried and failed), but was kinda hoping it'd be possible with `tokio`.

E.g. instead of this:
```rust
fn main() {
    let url = "https://replicate.npmjs.com/_changes".to_string();
    let mut changes = ChangesStream::new(url);

    changes.on(|change| {
        io::stdout().write_all(&change).unwrap();
    });

    changes.run();
}
```

I figured it'd be neat to be able to do this:
```rust
fn main() {
  let url = "https://replicate.npmjs.com/_changes".to_string();
  let mut changes = ChangesStream::new(url);
  let mut core = reactor::Core::new()

  changes.on(|change| {
    // And now for example we could use the same
    // core to do all sorts of timer stuff in here.
    io::stdout().write_all(&change).unwrap();
  });

  // slightly assuming core is able to run multiple things
  // and not just a single program; it'd be kinda moot otherwise hah
  core.run(changes);
}
```
I don't know; coming from Node I think I'm just very used to having a single event loop onto which all IO is attached; I was wondering if you'd have thoughts on this. Thanks heaps! :sparkles:

**Comment by steveklabnik** [comment]
Hey @yoshuawuyts !

So, first of all, this might not even be making the best use of tokio; we're open to general improvements. I feel like `-core` isn't necessarily the right place at the stack here; we'll figure it out.

But, beyond that, it was mostly trying to emulate the node api as close as possible. Since node's event loop is implicit, we tried to make it implicit. There's also not a reason we couldn't expose both....

**Comment by ashleygwilliams** [comment]
hey @yoshuawuyts ! so iirc when i was working on this with @seanmonstar we found that keeping the loop outside the changes-stream was forcing a lot of unnecessary complication in trying to coordinate communication between the client and the loop.

as @steveklabnik when we originally designed the interface, we had considered both interfaces- so it is def possible that it was just an issue we ran into while developing and we could get rid of it now. i might try that out now and see how it goes. 

fyi, PRs welcome, so if you ever wanna play around and suggest something, please do!

**Comment by ashleygwilliams** [comment]
@yoshuawuyts what do you think of https://github.com/ashleygwilliams/changes-stream-rust/pull/15/files?

**Comment by seanmonstar** [comment]
We worked on the original API so as to feel familiar to the Node API, but I do have some thoughts as to how it can feel more natural to the Rust futures landscape. The design I imagine would be to return a [`futures::Stream`](https://docs.rs/futures/0.1.8/futures/stream/trait.Stream.html), which allows consumers to pull items off when they want it. The current design doesn't allow that, so if a callback at some point cannot handle another change set, it has no way of signaling that.

Here's some code, since that speaks better than I do:

```rust
pub struct ChangeStream { .. }

impl ChangeStream {
    pub fn changes(&self) -> Changes {
        // details shmetails...
    }
}

pub struct Changes { .. }

impl Stream for Changes {
    type Item = Package;
    type Error = ChangesError;

    fn poll(&mut self) -> Poll<Package, ChangesError> {
        let chunk = try_ready!(self.hyper_response_body.poll());
        let package: Package = try!(serde::from_slice(&chunk));
        Ok(Async::Ready(Some(package)))
    }
}
```

Then, someone can consume the `Stream` when they want. It's simple to make it act like the current design, just use `stream.for_each(|package| ...)`, but it also means someone can ask for packages at a different rate.

```rust
let mut central_event_loop = Core::new().unwrap();
let stream = ChangeStream::new(url, &central_event_loop.handle());
let changes = stream.changes();

// there are other actions for a Stream than for_each, but this mimics current API
let work = changes.for_each(|package| {
    println!("package = {:?}", package);
    Ok(())
});

// use this thread to run this forever, like current design
central_event_loop.run(work);

// or, spawn this work onto the event loop, letting it run by whomever actually owns it
central_event_loop.handle().spawn(work);
```

**Comment by yoshuawuyts** [comment]
@ashleygwilliams nice, I'm digging it!
